### ISSUE TITLE
Impossible clock logic

### ISSUE THREAD

**Issue by tv42** [yrashk-archived/bpxe-go#64]
https://github.com/bpxe/bpxe/blob/0828554a14ebbdc2c38b7564443c0036b0f05ab0/pkg/clock/host_generic.go#L28

```
				if t1.Before(t1) {
```

You can be pretty darn sure that `t1` is never before itself.

**Comment by yrashk** [comment]
Thank you so much for this find! I've addressed it in #66. 

If you're following up on https://github.com/bpxe/bpxe/blob/master/CODEREVIEWS.md invitation, please send an email to
yrashk@aree.enterprises once you're done with your findings for the time being so we can tally them up and I'll be happy to
pay you out for your review. If this is the only thing you'll find so far, just send an email whenever you're ready!

**Comment by yrashk** [comment]
Resolved in #66
