### ISSUE TITLE
Outsiders cannot set issue labels

### ISSUE THREAD

**Issue by tv42** [yrashk-archived/bpxe-go#65]
https://github.com/bpxe/bpxe/blob/master/CODEREVIEWS.md#how-do-i-submit-reviews

> Simply open an issue and assign the `code review` label to it.

Without extra access to the repository, people cannot do that.

**Comment by yrashk** [comment]
That is a good point, thank you!

**Comment by yrashk** [comment]
Addressed in #67

**Comment by yrashk** [comment]
Resolved by #67
